### ISSUE TITLE
Licht nicht mehr schaltbar

### ISSUE THREAD

**Issue by Sec42** [muccc/spacefoo#90] opened 2017-03-22 18:19 UTC
karoshi:~>curl -X POST http://83.133.178.85:5000/relais/decke1
curl: (7) Failed to connect to 83.133.178.85 port 5000: No route to host

**Comment by schneider42** [comment] 2017-03-22 19:19
Duplicate of https://github.com/muccc/spacefoo/issues/77

**Closed as completed by schneider42** 2017-03-22 19:19 UTC
Labels: duplicate
